name: Sync Github To Gitee

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Sync Github To Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github
          dst: gitee
          dst_key: ${{ secrets.GITEE_TOKEN }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          clone_type: https
          force_update: true
          static_list: true
          timeout: 600
          config_files: repos.conf
