name: Sync Github To Gitee

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github User repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/heal2017
          dst: gitee/heal2017
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          force_update: true
          debug: true
          white_list: "heal2017,mihomo"
